name: CI/CD Django App

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: django-app

jobs:
  package:
    runs-on: self-hosted   
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Poetry
      run: pip install poetry

    - name: Package Django app
      run: poetry build
      working-directory: ${{ github.workspace }}/book-shop

    - name: Upload dist artifacts
      uses: actions/upload-artifact@v4
      with:
        name: django-dist
        path: book-shop/dist/*

  build:
    runs-on: self-hosted   
    needs: package
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: django-dist
        path: book-shop/dist

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image (with packaged app)
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} book-shop

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: self-hosted   
    needs: build
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_NAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker stop django-app || true
          docker rm django-app || true
          docker run -d -p 80:80 --name django-app ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

